---
language: ruby

rvm:
  - ruby-head
  - 2.5.0
  - 2.4.3
  - 2.3.5
  - 2.2.9
  - 2.1.10

before_install:
  - gem update --system
  - gem update bundler

install:
  - bundle install

script:
  - bundle exec rake --trace clobber compile
  - bundle exec rake spec
