---
language: ruby

rvm:
  - ruby-head
  - 2.3.0
  - 2.2.4
  - 2.1

before_install:
  - gem update --system
  - gem update bundler

install:
  - bundle install

script:
  - bundle exec rake clobber compile
  - bundle exec rake spec
