---
notification:
  email:
  - mrkn@ruby-lang.org

language: ruby

before_install:
  - yes | gem update --system
  - gem install bundler

install:
  - bundle install

script:
  - bundle exec rake --trace clobber compile
  - bundle exec rake spec

matrix:
  include:
    - name: "2.3"
      rvm: 2.3
    - name: "2.4"
      rvm: 2.4.5
    - name: "2.5"
      rvm: 2.5.2
    - name: "2.6"
      rvm: 2.6
    - name: "trunk"
      rvm: ruby-head
  allow_failures:
    - rvm: 2.3
