name: CI

on:
- push

jobs:
  cruby:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        ruby:
        - 3.3

    steps:
    - uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Detect installable bundler version
      run: |
        bundle install
        bundle exec rake compile
        cargo install fd-find
        fd -e dylib -x otool -L
        fd -e bunle -x otool -L
