name: CI

on:
- push

jobs:
  cruby:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        ruby_version:
        - 3.0.0-preview2
        - 2.7
        - 2.6
        - 2.5
        - 2.4
        - debug

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}

    - run: yes | gem update --system
    - run: gem install bundler
    - run: bundle install

    - run: rake --trace compile

    - run: rake build
    - run: gem install pkg/*gem

    - run: rake spec
