name: CI

on:
- push

jobs:
  cruby:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        ruby:
        - 3.0
        - 2.7
        - 2.6
        - 2.5
        - 2.4
        - debug
        exclude:
        - os: windows-latest
          ruby: 3.0
        - os: windows-latest
          ruby: debug

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - run: gem install bundler
    - run: bundle install

    - run: rake --trace compile

    - run: rake build
    - run: gem install pkg/*gem

    - run: rake
